
name: GitHub MATLAB Workflow
on: # You must define at least one trigger for each workflow.
  workflow_dispatch:  # Set manual triggers as an optional trigger.
  pull_request:       # Set pull_request as an automatic trigger. 
                      # By default, a pull_request runs when a pull_request 
                      # event's activity type is opened, synchronize, or reopened
    # opened: This triggers the workflow when a pull request is initially opened.
    # synchronize: This triggers the workflow when new commits are pushed to a pull request branch. This includes any time the pull request's head branch is updated with new commits.
    # reopened: This triggers the workflow when a previously closed pull request is reopened
    types: [opened, synchronize, reopened]
env:
  MW_SUPPORT_PACKAGE_ROOT: '/home/matlab/Documents/MATLAB/SupportPackages/R2024b'
  MW_RELATIVE_PROJECT_PATH: ''
  MW_PIPELINE_GEN_DIRECTORY: "_pipelineGen_" 
  # Note: You should never hardcode secrets or tokens in the YAML file.
  # For JFrog Artifactory storage services, you need to set the JFrog API token in GitHub repository secrets with the 'ARTIFACTORY_API_TOKEN_SECRET' ID. 
  # For S3 storage services, you need to set the AWS S3 access key in GitHub repository secrets with the 'S3_AWS_SECRET_ACCESS_KEY_SECRET' ID. 
  # For Azure Blob storage services, you need to set the Azure storage account connection string in GitHub repository secrets with the 'AZ_CONNECTION_STRING_SECRET' ID. 
jobs:
  build_files:
    runs-on: 'padv_wsl_agents' 
    container:
      image: 'slcicd.azurecr.io/slcheck/padv-ci:r2024b_apr25t_ci_spkg20250813' 
    env:
      HOME: /home/matlab
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy workflow files
        run: |
          mkdir "${{env.MW_RELATIVE_PROJECT_PATH}}${{env.MW_PIPELINE_GEN_DIRECTORY}}" 
          cp ".github/workflows/ir_dag.json" "${{env.MW_RELATIVE_PROJECT_PATH}}${{env.MW_PIPELINE_GEN_DIRECTORY}}/" 
          cp ".github/workflows/simulink_pipeline.yml" "${{env.MW_RELATIVE_PROJECT_PATH}}${{env.MW_PIPELINE_GEN_DIRECTORY}}/" 
      - name: Upload workflow files
        uses: actions/upload-artifact@v4
        with:
          name: workflow_generated_files
          path: ${{env.MW_RELATIVE_PROJECT_PATH}}${{env.MW_PIPELINE_GEN_DIRECTORY}}/
  
  start:
    needs: [build_files]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: start 
  
  padv_builtin_task_CollectMetrics_AHRS_Voter:
    needs: [start]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_CollectMetrics_AHRS_Voter 
  
  padv_builtin_task_GenerateSimulinkWebView_AHRS_Voter:
    needs: [padv_builtin_task_CollectMetrics_AHRS_Voter]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateSimulinkWebView_AHRS_Voter 
  
  padv_builtin_task_RunModelStandards_AHRS_Voter:
    needs: [padv_builtin_task_GenerateSimulinkWebView_AHRS_Voter]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_RunModelStandards_AHRS_Voter 
  
  FindAcrossModelClones_AHRS_Voter:
    needs: [padv_builtin_task_RunModelStandards_AHRS_Voter]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: FindAcrossModelClones_AHRS_Voter 
  
  FindLibraryClones_AHRS_Voter:
    needs: [FindAcrossModelClones_AHRS_Voter]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: FindLibraryClones_AHRS_Voter 
  
  padv_builtin_task_GenerateModelComparison_AHRS_Voter:
    needs: [FindLibraryClones_AHRS_Voter]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateModelComparison_AHRS_Voter 
  
  padv_builtin_task_RunTestsPerTestCase_AHRS_Voter:
    needs: [padv_builtin_task_GenerateModelComparison_AHRS_Voter]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_RunTestsPerTestCase_AHRS_Voter 
  
  padv_builtin_task_MergeTestResults_AHRS_Voter:
    needs: [padv_builtin_task_RunTestsPerTestCase_AHRS_Voter]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_MergeTestResults_AHRS_Voter 
  
  ModelTestingMetrics_AHRS_Voter:
    needs: [padv_builtin_task_MergeTestResults_AHRS_Voter]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: ModelTestingMetrics_AHRS_Voter 
  
  padv_builtin_task_GenerateCode_AHRS_Voter:
    needs: [ModelTestingMetrics_AHRS_Voter]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateCode_AHRS_Voter 
  
  padv_builtin_task_CollectMetrics_Actuator_Control:
    needs: [start]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_CollectMetrics_Actuator_Control 
  
  padv_builtin_task_GenerateSimulinkWebView_Actuator_Control:
    needs: [padv_builtin_task_CollectMetrics_Actuator_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateSimulinkWebView_Actuator_Control 
  
  padv_builtin_task_RunModelStandards_Actuator_Control:
    needs: [padv_builtin_task_GenerateSimulinkWebView_Actuator_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_RunModelStandards_Actuator_Control 
  
  FindAcrossModelClones_Actuator_Control:
    needs: [padv_builtin_task_RunModelStandards_Actuator_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: FindAcrossModelClones_Actuator_Control 
  
  FindLibraryClones_Actuator_Control:
    needs: [FindAcrossModelClones_Actuator_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: FindLibraryClones_Actuator_Control 
  
  padv_builtin_task_GenerateModelComparison_Actuator_Control:
    needs: [FindLibraryClones_Actuator_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateModelComparison_Actuator_Control 
  
  ModelTestingMetrics_Actuator_Control:
    needs: [padv_builtin_task_GenerateModelComparison_Actuator_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: ModelTestingMetrics_Actuator_Control 
  
  padv_builtin_task_GenerateCode_Actuator_Control:
    needs: [ModelTestingMetrics_Actuator_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateCode_Actuator_Control 
  
  padv_builtin_task_CollectMetrics_Flight_Control:
    needs: [start]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_CollectMetrics_Flight_Control 
  
  padv_builtin_task_GenerateSimulinkWebView_Flight_Control:
    needs: [padv_builtin_task_CollectMetrics_Flight_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateSimulinkWebView_Flight_Control 
  
  padv_builtin_task_RunModelStandards_Flight_Control:
    needs: [padv_builtin_task_GenerateSimulinkWebView_Flight_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_RunModelStandards_Flight_Control 
  
  FindAcrossModelClones_Flight_Control:
    needs: [padv_builtin_task_RunModelStandards_Flight_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: FindAcrossModelClones_Flight_Control 
  
  FindLibraryClones_Flight_Control:
    needs: [FindAcrossModelClones_Flight_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: FindLibraryClones_Flight_Control 
  
  padv_builtin_task_GenerateModelComparison_Flight_Control:
    needs: [FindLibraryClones_Flight_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateModelComparison_Flight_Control 
  
  padv_builtin_task_CollectMetrics_InnerLoop_Control:
    needs: [start]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_CollectMetrics_InnerLoop_Control 
  
  padv_builtin_task_GenerateSimulinkWebView_InnerLoop_Control:
    needs: [padv_builtin_task_CollectMetrics_InnerLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateSimulinkWebView_InnerLoop_Control 
  
  padv_builtin_task_RunModelStandards_InnerLoop_Control:
    needs: [padv_builtin_task_GenerateSimulinkWebView_InnerLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_RunModelStandards_InnerLoop_Control 
  
  FindAcrossModelClones_InnerLoop_Control:
    needs: [padv_builtin_task_RunModelStandards_InnerLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: FindAcrossModelClones_InnerLoop_Control 
  
  FindLibraryClones_InnerLoop_Control:
    needs: [FindAcrossModelClones_InnerLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: FindLibraryClones_InnerLoop_Control 
  
  padv_builtin_task_GenerateModelComparison_InnerLoop_Control:
    needs: [FindLibraryClones_InnerLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateModelComparison_InnerLoop_Control 
  
  ModelTestingMetrics_InnerLoop_Control:
    needs: [padv_builtin_task_GenerateModelComparison_InnerLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: ModelTestingMetrics_InnerLoop_Control 
  
  padv_builtin_task_GenerateCode_InnerLoop_Control:
    needs: [ModelTestingMetrics_InnerLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateCode_InnerLoop_Control 
  
  padv_builtin_task_CollectMetrics_OuterLoop_Control:
    needs: [start]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_CollectMetrics_OuterLoop_Control 
  
  padv_builtin_task_GenerateSimulinkWebView_OuterLoop_Control:
    needs: [padv_builtin_task_CollectMetrics_OuterLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateSimulinkWebView_OuterLoop_Control 
  
  padv_builtin_task_RunModelStandards_OuterLoop_Control:
    needs: [padv_builtin_task_GenerateSimulinkWebView_OuterLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_RunModelStandards_OuterLoop_Control 
  
  FindAcrossModelClones_OuterLoop_Control:
    needs: [padv_builtin_task_RunModelStandards_OuterLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: FindAcrossModelClones_OuterLoop_Control 
  
  FindLibraryClones_OuterLoop_Control:
    needs: [FindAcrossModelClones_OuterLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: FindLibraryClones_OuterLoop_Control 
  
  padv_builtin_task_GenerateModelComparison_OuterLoop_Control:
    needs: [FindLibraryClones_OuterLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateModelComparison_OuterLoop_Control 
  
  padv_builtin_task_RunTestsPerTestCase_OuterLoop_Control:
    needs: [padv_builtin_task_GenerateModelComparison_OuterLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_RunTestsPerTestCase_OuterLoop_Control 
  
  padv_builtin_task_MergeTestResults_OuterLoop_Control:
    needs: [padv_builtin_task_RunTestsPerTestCase_OuterLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_MergeTestResults_OuterLoop_Control 
  
  ModelTestingMetrics_OuterLoop_Control:
    needs: [padv_builtin_task_MergeTestResults_OuterLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: ModelTestingMetrics_OuterLoop_Control 
  
  padv_builtin_task_GenerateCode_OuterLoop_Control:
    needs: [ModelTestingMetrics_OuterLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateCode_OuterLoop_Control 
  
  Top_Model_Code_Generation:
    needs: [padv_builtin_task_GenerateCode_AHRS_Voter, padv_builtin_task_GenerateCode_Actuator_Control, padv_builtin_task_GenerateModelComparison_Flight_Control, padv_builtin_task_GenerateCode_InnerLoop_Control, padv_builtin_task_GenerateCode_OuterLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: Top_Model_Code_Generation 
  
  padv_builtin_task_GenerateRequirementsReport:
    needs: [Top_Model_Code_Generation]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateRequirementsReport 
  
