# Make sure to configure the following variables as repository variables and update the tokens below:
#   RUNNER_LABEL, PYTHON_ALIAS, SUPPORT_PACKAGE_ROOT, NETWORK_STORAGE_PATH
# To enable JFrog Artifactory storage services, you need to configure the following variables as repository variables:
#   ARTIFACT_SERVICE_MODE, ARTIFACTORY_URL, ARTIFACTORY_REPO_NAME, ARTIFACTORY_API_TOKEN_SECRET 
# To enable AWS S3 storage services, you need to configure the following variables as repository variables:
#   ARTIFACT_SERVICE_MODE, S3_BUCKET_NAME, S3_AWS_ACCESS_KEY_ID, S3_AWS_SECRET_ACCESS_KEY_SECRET
# To enable Azure Blob storage services, you need to configure the following variables as repository variables:
#   ARTIFACT_SERVICE_MODE, AZ_CONTAINER_NAME, AZ_CONNECTION_STRING_SECRET
name: GitHub MATLAB Workflow
on: # You must define at least one trigger for each workflow.
  workflow_dispatch:  # Set manual triggers as an optional trigger.
  pull_request:       # Set pull_request as an automatic trigger. 
                      # By default, a pull_request runs when a pull_request 
                      # event's activity type is opened, synchronize, or reopened
    # opened: This triggers the workflow when a pull request is initially opened.
    # synchronize: This triggers the workflow when new commits are pushed to a pull request branch. This includes any time the pull request's head branch is updated with new commits.
    # reopened: This triggers the workflow when a previously closed pull request is reopened
    types: [opened, synchronize, reopened]
    
jobs:
  build_files:
    runs-on: ${{ vars.RUNNER_LABEL }}
    env:
      BUILD_FOLDER_NAME: ${{ vars.BUILD_FOLDER_NAME || '_build_' }}
      PROJECT_RELATIVE_PATH: ${{ vars.PROJECT_RELATIVE_PATH || '' }}
      BUILD_FOLDER: "${{PROJECT_RELATIVE_PATH}}${{BUILD_FOLDER_NAME}}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: ${{ vars.SUBMODULES_MODE || 'false' }}
          fetch-depth: 0
      - name: Copy build files
        run: |
          mkdir "${{ env.BUILD_FOLDER }}" 
          cp ".github/workflows/ir_dag.json" "${{ env.BUILD_FOLDER }}/" 
          cp ".github/workflows/simulink_pipeline.yml" "${{ env.BUILD_FOLDER }}/" 
      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: build_files
          path: ${{ env.BUILD_FOLDER }}/
  
  start:
    needs: [build_files]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: start 
  
  padv_builtin_task_CollectMetrics_AHRS_Voter:
    needs: [start]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_CollectMetrics_AHRS_Voter 
  
  padv_builtin_task_GenerateSimulinkWebView_AHRS_Voter:
    needs: [padv_builtin_task_CollectMetrics_AHRS_Voter]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateSimulinkWebView_AHRS_Voter 
  
  padv_builtin_task_CollectMetrics_Actuator_Control:
    needs: [start]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_CollectMetrics_Actuator_Control 
  
  padv_builtin_task_GenerateSimulinkWebView_Actuator_Control:
    needs: [padv_builtin_task_CollectMetrics_Actuator_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateSimulinkWebView_Actuator_Control 
  
  padv_builtin_task_CollectMetrics_Flight_Control:
    needs: [start]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_CollectMetrics_Flight_Control 
  
  padv_builtin_task_GenerateSimulinkWebView_Flight_Control:
    needs: [padv_builtin_task_CollectMetrics_Flight_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateSimulinkWebView_Flight_Control 
  
  padv_builtin_task_CollectMetrics_InnerLoop_Control:
    needs: [start]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_CollectMetrics_InnerLoop_Control 
  
  padv_builtin_task_GenerateSimulinkWebView_InnerLoop_Control:
    needs: [padv_builtin_task_CollectMetrics_InnerLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateSimulinkWebView_InnerLoop_Control 
  
  padv_builtin_task_CollectMetrics_OuterLoop_Control:
    needs: [start]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_CollectMetrics_OuterLoop_Control 
  
  padv_builtin_task_GenerateSimulinkWebView_OuterLoop_Control:
    needs: [padv_builtin_task_CollectMetrics_OuterLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateSimulinkWebView_OuterLoop_Control 
  
  padv_builtin_task_GenerateRequirementsReport_HighLevelReqs:
    needs: [padv_builtin_task_GenerateSimulinkWebView_AHRS_Voter, padv_builtin_task_GenerateSimulinkWebView_Actuator_Control, padv_builtin_task_GenerateSimulinkWebView_Flight_Control, padv_builtin_task_GenerateSimulinkWebView_InnerLoop_Control, padv_builtin_task_GenerateSimulinkWebView_OuterLoop_Control]
    uses: ./.github/workflows/generic-job.yml
    secrets: inherit
    with:
      job-name: padv_builtin_task_GenerateRequirementsReport_HighLevelReqs 
  
